export type DocumentType = 'NFE' | 'CTE' | 'NFSE' | 'UNKNOWN';
export type TaxRegime = 'SIMPLES_NACIONAL' | 'RPA' | 'RPA' | 'UNKNOWN';
export type DocumentStatus = 'VALID' | 'SCHEMA_ERROR' | 'PARTIAL';

export type DocumentDirection = 'INBOUND' | 'OUTBOUND' | 'UNKNOWN';
export type DocumentPurpose = 'NORMAL' | 'COMPLEMENTAR' | 'AJUSTE' | 'DEVOLUCAO' | 'UNKNOWN';
export type CfopCategory = 'SALE' | 'RETURN' | 'TRANSFER' | 'OTHER';
export type RtcImpact = 'CREDIT' | 'DEBIT' | 'NEUTRAL';

export interface Participant {
  cnpj_cpf: string;
  name: string;
  ie?: string;
  uf?: string;
}

export interface ItemTaxesRTC {
  cst?: string;
  c_class_trib?: string;
  vBC?: number;
  pIBSUF?: number;
  vIBSUF?: number;
  pIBSMun?: number;
  vIBSMun?: number;
  vIBS?: number;
  pCBS?: number;
  vCBS?: number;
}

export interface ItemTaxesCurrent {
  icms_cst?: string;
  icms_base?: number;
  icms_rate?: number;
  icms_value?: number;
  pis_cst?: string;
  pis_base?: number;
  pis_rate?: number;
  pis_value?: number;
  cofins_cst?: string;
  cofins_base?: number;
  cofins_rate?: number;
  cofins_value?: number;
  ipi_cst?: string;
  ipi_base?: number;
  ipi_rate?: number;
  ipi_value?: number;
}

export interface DocumentItem {
  item_number: number;
  description: string;
  cfop: string;
  ncm: string;
  gross_value: number;
  discount_value: number;
  net_value: number;
  taxes_current: ItemTaxesCurrent;
  rtc: ItemTaxesRTC;
  cfop_category?: CfopCategory;
  rtc_impact?: RtcImpact;
}

export interface DocumentTotals {
  vProd: number;
  vDesc: number;
  vFrete: number;
  vSeg: number;
  vOutro: number;
  vTotTrib: number;
  vICMS: number;
  vPIS: number;
  vCOFINS: number;
  vBCIBSCBS?: number;
  vIBS?: number;
  vCBS?: number;
}

export interface FiscalDocument {
  id?: string; // Will be generated by DB later
  access_key: string;
  document_type: DocumentType;
  version: string;
  issue_date: string;
  issuer: Participant;
  receiver: Participant;
  sender?: Participant; // Used mostly in CTe
  tax_regime: TaxRegime;
  total_value: number;
  totals: DocumentTotals;
  status: DocumentStatus;
  items: DocumentItem[];
  referenced_keys?: string[]; // Used mostly in CTe
  raw_xml?: string; // Stored for audit
  file_hash?: string;
  direction?: DocumentDirection;
  purpose?: DocumentPurpose;
}

export interface ProcessingLog {
  level: 'INFO' | 'WARN' | 'ERROR' | 'FATAL';
  category: 'SCHEMA' | 'PARSE' | 'BUSINESS_RULE';
  message: string;
}

export interface ParseResult {
  document: FiscalDocument | null;
  logs: ProcessingLog[];
  success: boolean;
}
